# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "dark"

# Site Settings
locale                   : "zh-CN"
title                    : "UltBlog"
title_separator          : "|"
subtitle                 : "Welcome"
name                     : "Ultcrt"
description              : "My personal blog site based on Jekyll and minimal-mistakes."
url                      : "https://ultcrt.github.io/"
baseurl                  : "/UltBlog"
repository               : "Ultcrt/ultcrt.github.io"
teaser                   : "/assets/images/site/default-teaser.png"
logo                     : "/assets/images/site/site-logo-transparent.png"
masthead_title           : "Ultcrt的博客"
words_per_minute         : 200
comments:
  provider               : "giscus"
  giscus:
    repo_id              : "R_kgDOKIgaLg"
    category_name        : "Announcements"
    category_id          : "DIC_kwDOKIgaLs4CYtL9"
    discussion_term      : "pathname"
    reactions_enabled    : "1"
    theme                : "dark"
atom_feed:
  path                   : # blank (default) uses feed.xml
  hide                   : false
search                   : true
search_full_content      : true # Will override lunr.search_within_pages and could impact page load performance.
search_provider          : lunr

# SEO Related
google_site_verification : "GptLjqC2dp-6bfas7WQVmtwL7brtrcUNOXuYKH5MCcs"
bing_site_verification   :
naver_site_verification  :
yandex_site_verification :
baidu_site_verification  :

# Social Sharing
twitter:
  username               : "Ultcrt"
facebook:
  username               : "Ultcrt"
  app_id                 :
  publisher              :
og_image                 : "/assets/images/site/open-graph-default.png"
social:
  type                   : "Person"
  name                   : "Ultcrt"
  links: 
    - "https://ultcrt.github.io/UltBlog/"
    - "https://github.com/Ultcrt"
    - "https://gitee.com/Ultcrt"
    - "https://space.bilibili.com/6060911"

# Analytics
analytics:
  provider               : "google-gtag"
  google:
    tracking_id          : "G-YHYGFV50FH"
    anonymize_ip         : false


# Site Author
author:
  name             : "Ultcrt"
  avatar           : "/assets/images/site/site-logo.png"
  bio              : "基于 Jekyll 和 minimal-mistakes 的个人博客。"
  location         : "浙江 杭州"
  email            : "zhang_zhe_yuan@outlook.com"
  links:
    - label: "Github"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Ultcrt"
    - label: "Gitee"
      icon: "fas fa-fw fa-warehouse"
      url: "https://gitee.com/Ultcrt"
    - label: "BiliBili"
      icon: "fas fa-fw fa-play"
      url: "https://space.bilibili.com/6060911"
    - label: "Steam"
      icon: "fab fa-fw fa-steam"
      url: "https://steamcommunity.com/id/Ultcrt"

# Site Footer
footer:
  links:
    - label: "Github"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Ultcrt"
    - label: "Gitee"
      icon: "fas fa-fw fa-warehouse"
      url: "https://gitee.com/Ultcrt"
    - label: "BiliBili"
      icon: "fas fa-fw fa-play"
      url: "https://space.bilibili.com/6060911"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:zhang_zhe_yuan@outlook.com"
    - label: "Steam"
      icon: "fab fa-fw fa-steam"
      url: "https://steamcommunity.com/id/Ultcrt"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: "Asia/Shanghai"


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache


# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
      toc: true
      toc_label: "Contents"

date_format: "%Y-%m-%d"