backend:
  name: github
  branch: master
  repo: Ultcrt/UltBlog

publish_mode: editorial_workflow

media_folder: "/assets/images/uploads"
public_folder: "UltBlog/assets/images/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "/_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Last Modified Date", name: "last_modified_at", widget: "datetime"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Tags", name: "tags", widget: "list"}
      - label: "Header"
        name: "header"
        widget: "object"
        fields:
          - {label: "Overlay Image", name: "overlay_image", widget: "image", default: "https://picsum.photos/1920/640"}
          - {label: "Caption", name: "caption", widget: "string", default: "来源: [**Lorem Picsum**](https://picsum.photos/)"}
          - {label: "Teaser", name: "teaser", widget: "image", default: "/assets/images/site/default-teaser.png"}
      - {label: "Body", name: "body", widget: "markdown"}